### PR TITLE
dns: update CAA now that we're using BIND >= 9.9.6

### PR DESCRIPTION
**Pull request by abizer**

### CODE REVIEW

**Comment by chriskuehl** [comment]
bump serials too? just run `make` imo

as-is, if you merge this, nothing will change, and if this happens to be broken, we won't notice until the next time someone tries to push out new unrelated dns configs

**Comment by abizer** [comment]
Oh shoot, nice catch, can't believe I forgot about that.

**Comment by jvperrin** [comment]
That being said, currently the propagation seems broken again anyway, probably due to DNSSEC if I had to guess.

**Comment by jvperrin** [comment]
You'll want to run `make` on this again since I pushed conflicting changes and the serial will be behind now :(

**Pull request merged**
