### PR TITLE
Add back forgotten hostnames

### PR DESCRIPTION
**Pull request by daradib**
We lost a few hostnames in the past few years, so add
them back to the unused list. Of particular note are
apocalypse and conquest, which were the twin login servers
before tsunami, and part of a long-lived reference to the
Four Horsemen of the Apocalypse - the others being
death, famine, pestilence, and war, which still exist.

In 2011 we also considered adding the following hostnames:
blackice
budgetcut
bushfire
cavein
cloudburst
collision
deathbymonkeys
doom
lotso
oilspill
shipwreck
spike
strike
thunderstorm
walkout

### CODE REVIEW

**Comment by daradib** [comment]
> you edited the autogenerated file

Haha woops, will fix.

**Comment by daradib** [comment]
Any objections to the list of hostnames from 2011? Feel free to nuke some bad choices.

**Comment by chriskuehl** [comment]
lol list looks good to me, better merge quickly though, these new kids won't get any of the references

**Comment by jvperrin** [comment]
Nice, these are good! I'd add the suggested ones too, they are pretty good, although why `deathbymonkeys`? Seems awfully specific... `lotso` also fits with the Debian theme but seems kinda obscure.

Also we have a `thunder` now (to go with `lightning`), so `thunderstorm` is pretty similar to that already.

**Comment by jvperrin** [comment]
(though fair enough we do have both a `fire` and `firestorm` currently)

**Comment by daradib** [comment]
@jvperrin feel free to remove lotso and thunderstorm. As for deathbymonkeys, best to ask @syjk, probably a Toy Story 3 reference.

**Comment by jvperrin** [comment]
That's fine, can just go with it as it is, they are just suggestions after all. [Seems likely on the monkeys](http://pixar.wikia.com/wiki/Barrel_of_Monkeys)

**Comment by gnowxilef** [comment]
where did you even find these names?

**Comment by daradib** [comment]
Old emails from ~5 years ago. There was a list of DNS records and a
discussion about hostnames.

**Pull request merged**
