### PR TITLE
Add * record for pox

### PR DESCRIPTION
**Pull request by mcint**

### CODE REVIEW

**Comment by matthew-mcallister** [comment]
I don't have any concerns with this. @chriskuehl @jvperrin anything?

**Comment by jvperrin** [comment]
Yeah, I checked it was from LDAP

**Comment by matthew-mcallister** [comment]
So, I don't think the SSL cert for pox will be valid for these subdomains. If not, and if you care about having a non-self-signed cert, we may be able to request a star cert.

**Comment by chriskuehl** [comment]
yea, we can request free wildcard certs if necessary

**Comment by jvperrin** [comment]
This was done by ab84983, so this should be closed. Should have been merged before, but oh well...

**Pull request closed without merging**
