### PR TITLE
Remove squelched DNS zone

### PR DESCRIPTION
**Pull request by daradib**
$ whois squelched.com
[...]
   Name Server: DNS1.REGISTRAR-SERVERS.COM
   Name Server: DNS2.REGISTRAR-SERVERS.COM

### CODE REVIEW

**Comment by daradib** [comment]
With a few exceptions (ourselves and ASUC), I suggest not offering external DNS hosting. It's typically included in domain registration (which we are not responsible for maintaining/renewing) or minimal additional cost, and there a few downsides (we think we're authoritative when we're not - this broke decal.org on campus ~5 years ago, DNS amplification attacks).

**Comment by chriskuehl** [comment]
i'm ambivalent about this

i agree it's not a great thing for us to offer, but i also don't want to have to coordinate with groups when we change our own IP addresses (since, sadly, they can't just cname to death). i guess that's rare enough, but still annoying to have to do.

**Comment by daradib** [comment]
However, since we can't force them to use our DNS, they might change their nameserver unknowingly and from our end it would seem normal.

Speaking of which,

    $ dig +short squelched.com mx
    10 sandstorm.ocf.berkeley.edu.

**Comment by chriskuehl** [comment]
squelched never actually started using our nameserver. there was a long thread where they gave some nonsensical answer from their domain registrar about how our nameservers weren't in some global list of nameservers (wat) and then they just gave up.

**Comment by jvperrin** [comment]
They also don't have IPv6, I tried to add it here, but obviously we weren't authoritative for their DNS, so it didn't work.

**Comment by chriskuehl** [comment]
https://ocf.io/rt/3690 for the curious

**Comment by daradib** [comment]
As I understand their registrar only allows name servers with glue records in the root, which we don't have. We could get a glue record for ns{1,2}.ocf.io through Namecheap.

**Comment by chriskuehl** [comment]
i don't really feel like it's worth additional effort on our part to try to get them to switch, idk

we should get them to switch from sandstorm though at least, since we will remove that record soon

**Pull request merged**
